describe('CSV Parser', () => {
    let csvtojsonMock
    let csvtojsonObjectMock = {}
    let CSVParser

    before(() => {
        csvtojsonObjectMock.fromString = stub().returns(csvtojsonObjectMock)
        csvtojsonObjectMock.on = stub().returns(csvtojsonObjectMock)
        csvtojsonMock = stub().returns(csvtojsonObjectMock)

        CSVParser = proxyquire('src/libs/csv-parser.js', {
            'csvtojson': csvtojsonMock
        })
    })

    it('should call external functions correctly', () => {
        CSVParser('TEST_CSV_STRING')
        expect(csvtojsonMock).to.have.been.calledWithMatch({noheader: true})
        expect(csvtojsonObjectMock.fromString).to.have.been.calledWith('TEST_CSV_STRING')
        expect(csvtojsonObjectMock.on).to.have.been.calledWithMatch('csv', sinon.match.func)
        expect(csvtojsonObjectMock.on).to.have.been.calledWithMatch('done', sinon.match.func)
    })

    it('should parse correctly', () => {
        let done = false
        let doneHandle
        let mockCSV = [
            ['Obesity Prevalence','','','2004','','','','','','','2005','','','','','','','2006','','','','','','','2007','','','','','','','2008','','','','','','','2009','','','','','','','2010','','','','','','','2011','','','','','','','2012','','','','','','','2013','','','','','',''],
            ['State','FIPS Codes','County','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit','number','percent','lower confidence limit','upper confidence limit','age-adjusted percent','age-adjusted lower confidence limit','age-adjusted upper confidence limit'],
            ['Alabama','01001','Autauga County','10180','30.2','24.7','36.5','29.8','24.4','36.2','10050','28.87','23.72','34.97','28.53','23.42','34.55','9912','27.9','22.8','33.5','27.5','22.5','33.1','10640','30','24.6','36','29.8','24.4','35.8','11350','31.5','26.2','37.6','31.3','26','37.4','12024','34.1','28.7','39.9','33.9','28.6','39.7','11761','30.5','25.5','35.7','30.4','25.3','35.5','12340','31.3','26.4','36.3','31.1','26.1','36.2','12184','30.9','25.9','35.8','30.7','25.5','35.7','13513','34.1','29','39.3','33.8','28.7','39.2'],
            ['Alabama','01003','Baldwin County','30120','25.7','21.7','30.3','25.9','21.7','30.7','30710','25.11','21.16','29.54','25.22','21.12','29.87','30460','23.9','20.5','27.8','24','20.4','28','31240','24.5','21.1','28.1','24.6','21','28.4','33960','26.2','23','29.7','26.3','23','30.1','34244','25.5','22.6','28.5','25.7','22.5','28.8','36348','26.6','23.7','29.6','26.8','23.8','30.1','35005','25','22.3','28','24.9','22','28','38245','26.7','23.8','29.7','26.6','23.5','29.8','40365','27.4','24.8','30.5','27.2','24.3','30.6'],
            ['Alabama','01005','Barbour County','6645','31.7','26','38.1','31.6','25.9','38.1','6972','33.04','27.11','40.08','32.96','26.94','40.14','7595','36.5','30.1','43.9','36.4','29.8','43.9','7591','36.4','30.4','43.1','36.3','30.3','43.2','8240','37.6','32','43.8','37.5','31.8','43.9','8264','37','31.8','42.2','37.1','31.8','42.4','7743','37.3','32.1','42.6','37.4','32','42.9','8021','38.4','32.7','44.2','38.5','32.5','44.5','8482','40.8','34.9','46.6','40.9','34.6','47','9186','44.4','38.4','50.4','44.7','38.5','51.1']
        ]
        csvtojsonObjectMock.on = spy((type, handle) => {
            if(type === 'csv') {
                mockCSV.forEach(handle)
                done = true
                if(doneHandle) doneHandle()
            } else if(type === 'done') {
                doneHandle = handle
                if(done) doneHandle()
            }

            return csvtojsonObjectMock
        })

        expect(CSVParser('TEST_CSV_STRING')).to.eventually.deep.equal([
            {
                state: 'Alabama',
                name: 'Autauga County',
                fips: '01001',
                years: [
                    { year: 2004,
                      number: '10180',
                      percent: '30.2',
                      lowerConfidenceLimit: '24.7',
                      upperConfidenceLimit: '36.5',
                      ageAjustedPercent: '29.8',
                      ageAjustedLowerConfidenceLimit: '24.4',
                      ageAjustedUpperConfidenceLimit: '36.2' },
                    { year: 2005,
                      number: '10050',
                      percent: '28.87',
                      lowerConfidenceLimit: '23.72',
                      upperConfidenceLimit: '34.97',
                      ageAjustedPercent: '28.53',
                      ageAjustedLowerConfidenceLimit: '23.42',
                      ageAjustedUpperConfidenceLimit: '34.55' },
                    { year: 2006,
                      number: '9912',
                      percent: '27.9',
                      lowerConfidenceLimit: '22.8',
                      upperConfidenceLimit: '33.5',
                      ageAjustedPercent: '27.5',
                      ageAjustedLowerConfidenceLimit: '22.5',
                      ageAjustedUpperConfidenceLimit: '33.1' },
                    { year: 2007,
                      number: '10640',
                      percent: '30',
                      lowerConfidenceLimit: '24.6',
                      upperConfidenceLimit: '36',
                      ageAjustedPercent: '29.8',
                      ageAjustedLowerConfidenceLimit: '24.4',
                      ageAjustedUpperConfidenceLimit: '35.8' },
                    { year: 2008,
                      number: '11350',
                      percent: '31.5',
                      lowerConfidenceLimit: '26.2',
                      upperConfidenceLimit: '37.6',
                      ageAjustedPercent: '31.3',
                      ageAjustedLowerConfidenceLimit: '26',
                      ageAjustedUpperConfidenceLimit: '37.4' },
                    { year: 2009,
                      number: '12024',
                      percent: '34.1',
                      lowerConfidenceLimit: '28.7',
                      upperConfidenceLimit: '39.9',
                      ageAjustedPercent: '33.9',
                      ageAjustedLowerConfidenceLimit: '28.6',
                      ageAjustedUpperConfidenceLimit: '39.7' },
                    { year: 2010,
                      number: '11761',
                      percent: '30.5',
                      lowerConfidenceLimit: '25.5',
                      upperConfidenceLimit: '35.7',
                      ageAjustedPercent: '30.4',
                      ageAjustedLowerConfidenceLimit: '25.3',
                      ageAjustedUpperConfidenceLimit: '35.5' },
                    { year: 2011,
                      number: '12340',
                      percent: '31.3',
                      lowerConfidenceLimit: '26.4',
                      upperConfidenceLimit: '36.3',
                      ageAjustedPercent: '31.1',
                      ageAjustedLowerConfidenceLimit: '26.1',
                      ageAjustedUpperConfidenceLimit: '36.2' },
                    { year: 2012,
                      number: '12184',
                      percent: '30.9',
                      lowerConfidenceLimit: '25.9',
                      upperConfidenceLimit: '35.8',
                      ageAjustedPercent: '30.7',
                      ageAjustedLowerConfidenceLimit: '25.5',
                      ageAjustedUpperConfidenceLimit: '35.7' },
                    { year: 2013,
                      number: '13513',
                      percent: '34.1',
                      lowerConfidenceLimit: '29',
                      upperConfidenceLimit: '39.3',
                      ageAjustedPercent: '33.8',
                      ageAjustedLowerConfidenceLimit: '28.7',
                      ageAjustedUpperConfidenceLimit: '39.2' }
                ]
            },
            {
                state: 'Alabama',
                fips: '01003',
                name: 'Baldwin County',
                years: [
                    { year: 2004,
                      number: '30120',
                      percent: '25.7',
                      lowerConfidenceLimit: '21.7',
                      upperConfidenceLimit: '30.3',
                      ageAjustedPercent: '25.9',
                      ageAjustedLowerConfidenceLimit: '21.7',
                      ageAjustedUpperConfidenceLimit: '30.7' },
                    { year: 2005,
                      number: '30710',
                      percent: '25.11',
                      lowerConfidenceLimit: '21.16',
                      upperConfidenceLimit: '29.54',
                      ageAjustedPercent: '25.22',
                      ageAjustedLowerConfidenceLimit: '21.12',
                      ageAjustedUpperConfidenceLimit: '29.87' },
                    { year: 2006,
                      number: '30460',
                      percent: '23.9',
                      lowerConfidenceLimit: '20.5',
                      upperConfidenceLimit: '27.8',
                      ageAjustedPercent: '24',
                      ageAjustedLowerConfidenceLimit: '20.4',
                      ageAjustedUpperConfidenceLimit: '28' },
                    { year: 2007,
                      number: '31240',
                      percent: '24.5',
                      lowerConfidenceLimit: '21.1',
                      upperConfidenceLimit: '28.1',
                      ageAjustedPercent: '24.6',
                      ageAjustedLowerConfidenceLimit: '21',
                      ageAjustedUpperConfidenceLimit: '28.4' },
                    { year: 2008,
                      number: '33960',
                      percent: '26.2',
                      lowerConfidenceLimit: '23',
                      upperConfidenceLimit: '29.7',
                      ageAjustedPercent: '26.3',
                      ageAjustedLowerConfidenceLimit: '23',
                      ageAjustedUpperConfidenceLimit: '30.1' },
                    { year: 2009,
                      number: '34244',
                      percent: '25.5',
                      lowerConfidenceLimit: '22.6',
                      upperConfidenceLimit: '28.5',
                      ageAjustedPercent: '25.7',
                      ageAjustedLowerConfidenceLimit: '22.5',
                      ageAjustedUpperConfidenceLimit: '28.8' },
                    { year: 2010,
                      number: '36348',
                      percent: '26.6',
                      lowerConfidenceLimit: '23.7',
                      upperConfidenceLimit: '29.6',
                      ageAjustedPercent: '26.8',
                      ageAjustedLowerConfidenceLimit: '23.8',
                      ageAjustedUpperConfidenceLimit: '30.1' },
                    { year: 2011,
                      number: '35005',
                      percent: '25',
                      lowerConfidenceLimit: '22.3',
                      upperConfidenceLimit: '28',
                      ageAjustedPercent: '24.9',
                      ageAjustedLowerConfidenceLimit: '22',
                      ageAjustedUpperConfidenceLimit: '28' },
                    { year: 2012,
                      number: '38245',
                      percent: '26.7',
                      lowerConfidenceLimit: '23.8',
                      upperConfidenceLimit: '29.7',
                      ageAjustedPercent: '26.6',
                      ageAjustedLowerConfidenceLimit: '23.5',
                      ageAjustedUpperConfidenceLimit: '29.8' },
                    { year: 2013,
                      number: '40365',
                      percent: '27.4',
                      lowerConfidenceLimit: '24.8',
                      upperConfidenceLimit: '30.5',
                      ageAjustedPercent: '27.2',
                      ageAjustedLowerConfidenceLimit: '24.3',
                      ageAjustedUpperConfidenceLimit: '30.6' }
                ]
            },
            {
                state: 'Alabama',
                fips: '01005',
                name: 'Barbour County',
                years: [
                    { year: 2004,
                      number: '6645',
                      percent: '31.7',
                      lowerConfidenceLimit: '26',
                      upperConfidenceLimit: '38.1',
                      ageAjustedPercent: '31.6',
                      ageAjustedLowerConfidenceLimit: '25.9',
                      ageAjustedUpperConfidenceLimit: '38.1' },
                    { year: 2005,
                      number: '6972',
                      percent: '33.04',
                      lowerConfidenceLimit: '27.11',
                      upperConfidenceLimit: '40.08',
                      ageAjustedPercent: '32.96',
                      ageAjustedLowerConfidenceLimit: '26.94',
                      ageAjustedUpperConfidenceLimit: '40.14' },
                    { year: 2006,
                      number: '7595',
                      percent: '36.5',
                      lowerConfidenceLimit: '30.1',
                      upperConfidenceLimit: '43.9',
                      ageAjustedPercent: '36.4',
                      ageAjustedLowerConfidenceLimit: '29.8',
                      ageAjustedUpperConfidenceLimit: '43.9' },
                    { year: 2007,
                      number: '7591',
                      percent: '36.4',
                      lowerConfidenceLimit: '30.4',
                      upperConfidenceLimit: '43.1',
                      ageAjustedPercent: '36.3',
                      ageAjustedLowerConfidenceLimit: '30.3',
                      ageAjustedUpperConfidenceLimit: '43.2' },
                    { year: 2008,
                      number: '8240',
                      percent: '37.6',
                      lowerConfidenceLimit: '32',
                      upperConfidenceLimit: '43.8',
                      ageAjustedPercent: '37.5',
                      ageAjustedLowerConfidenceLimit: '31.8',
                      ageAjustedUpperConfidenceLimit: '43.9' },
                    { year: 2009,
                      number: '8264',
                      percent: '37',
                      lowerConfidenceLimit: '31.8',
                      upperConfidenceLimit: '42.2',
                      ageAjustedPercent: '37.1',
                      ageAjustedLowerConfidenceLimit: '31.8',
                      ageAjustedUpperConfidenceLimit: '42.4' },
                    { year: 2010,
                      number: '7743',
                      percent: '37.3',
                      lowerConfidenceLimit: '32.1',
                      upperConfidenceLimit: '42.6',
                      ageAjustedPercent: '37.4',
                      ageAjustedLowerConfidenceLimit: '32',
                      ageAjustedUpperConfidenceLimit: '42.9' },
                    { year: 2011,
                      number: '8021',
                      percent: '38.4',
                      lowerConfidenceLimit: '32.7',
                      upperConfidenceLimit: '44.2',
                      ageAjustedPercent: '38.5',
                      ageAjustedLowerConfidenceLimit: '32.5',
                      ageAjustedUpperConfidenceLimit: '44.5' },
                    { year: 2012,
                      number: '8482',
                      percent: '40.8',
                      lowerConfidenceLimit: '34.9',
                      upperConfidenceLimit: '46.6',
                      ageAjustedPercent: '40.9',
                      ageAjustedLowerConfidenceLimit: '34.6',
                      ageAjustedUpperConfidenceLimit: '47' },
                    { year: 2013,
                      number: '9186',
                      percent: '44.4',
                      lowerConfidenceLimit: '38.4',
                      upperConfidenceLimit: '50.4',
                      ageAjustedPercent: '44.7',
                      ageAjustedLowerConfidenceLimit: '38.5',
                      ageAjustedUpperConfidenceLimit: '51.1' }
                ]
            }
        ])
    })
})
